# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-23 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
